import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as prime  from 'primeng/primeng';
import {TableModule} from 'primeng/table';
@NgModule({
  providers:
  [

    
  ],
  imports: [
CommonModule

,prime.AccordionModule
,prime.AutoCompleteModule
,prime.BlockUIModule
,prime.BreadcrumbModule
,prime.ButtonModule
,prime.CaptchaModule
,prime.CalendarModule
,prime.CardModule
,prime.CarouselModule
,prime.ChartModule
,prime.CheckboxModule
,prime.ChipsModule
,prime.CodeHighlighterModule
,prime.ColorPickerModule
,prime.ConfirmDialogModule
,prime.ContextMenuModule
,prime.DataGridModule
,prime.DataListModule
,prime.DataScrollerModule
,prime.DataTableModule
,TableModule
,prime.DeferModule
,prime.DialogModule
,prime.DragDropModule
,prime.DropdownModule
,prime.EditorModule
,prime.FieldsetModule
,prime.FileUploadModule
,prime.GalleriaModule
,prime.GMapModule
,prime.GrowlModule
,prime.InplaceModule
,prime.InputMaskModule
,prime.InputSwitchModule
,prime.InputTextModule
,prime.InputTextareaModule
,prime.KeyFilterModule
,prime.LightboxModule
,prime.ListboxModule
,prime.MegaMenuModule
,prime.MenuModule
,prime.MenubarModule
,prime.MessagesModule
,prime.MessageModule
,prime.MultiSelectModule
,prime.OrderListModule
,prime.OrganizationChartModule
,prime.OverlayPanelModule
,prime.PaginatorModule
,prime.PanelModule
,prime.PanelMenuModule
,prime.PasswordModule
,prime.PickListModule
,prime.ProgressBarModule
,prime.ProgressSpinnerModule
,prime.RadioButtonModule
,prime.RatingModule
,prime.ScheduleModule
,prime.ScrollPanelModule
,prime.SelectButtonModule
,prime.SlideMenuModule
,prime.SliderModule
,prime.SidebarModule
,prime.SpinnerModule
,prime.SplitButtonModule
,prime.StepsModule
,prime.TabViewModule
,prime.TabMenuModule
,prime.TerminalModule
,prime.TieredMenuModule
,prime.ToggleButtonModule
,prime.ToolbarModule
,prime.TooltipModule
,prime.TreeModule
,prime.TreeTableModule
,prime.TriStateCheckboxModule


  ],
  exports:[
prime.AccordionModule
,prime.AutoCompleteModule
,prime.BlockUIModule
,prime.BreadcrumbModule
,prime.ButtonModule
,prime.CaptchaModule
,prime.CalendarModule
,prime.CardModule
,prime.CarouselModule
,prime.ChartModule
,prime.CheckboxModule
,prime.ChipsModule
,prime.CodeHighlighterModule
,prime.ColorPickerModule
,prime.ConfirmDialogModule                          
,prime.ContextMenuModule
,prime.DataGridModule
,prime.DataListModule
,prime.DataScrollerModule
,prime.DataTableModule
,TableModule
,prime.DeferModule
,prime.DialogModule
,prime.DragDropModule
,prime.DropdownModule
,prime.EditorModule
,prime.FieldsetModule
,prime.FileUploadModule
,prime.GalleriaModule
,prime.GMapModule
,prime.GrowlModule
,prime.InplaceModule
,prime.InputMaskModule
,prime.InputSwitchModule
,prime.InputTextModule
,prime.InputTextareaModule
,prime.KeyFilterModule
,prime.LightboxModule
,prime.ListboxModule
,prime.MegaMenuModule
,prime.MenuModule
,prime.MenubarModule
,prime.MessagesModule
,prime.MessageModule
,prime.MultiSelectModule
,prime.OrderListModule
,prime.OrganizationChartModule
,prime.OverlayPanelModule
,prime.PaginatorModule
,prime.PanelModule
,prime.PanelMenuModule
,prime.PasswordModule
,prime.PickListModule
,prime.ProgressBarModule
,prime.ProgressSpinnerModule
,prime.RadioButtonModule
,prime.RatingModule
,prime.ScheduleModule
,prime.ScrollPanelModule
,prime.SelectButtonModule
,prime.SlideMenuModule
,prime.SliderModule
,prime.SidebarModule
,prime.SpinnerModule
,prime.SplitButtonModule
,prime.StepsModule
,prime.TabViewModule
,prime.TabMenuModule
,prime.TerminalModule
,prime.TieredMenuModule
,prime.ToggleButtonModule
,prime.ToolbarModule
,prime.TooltipModule
,prime.TreeModule
,prime.TreeTableModule
,prime.TriStateCheckboxModule
  ],
  declarations: []
})
export class PrimeModule { }
